blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('<slug:category_slug>/', views.category_posts, name='category_posts'),
]

blogicum/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block page_header %}
        {% endblock %}
        {% block content %}
        {% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}

{% block title %}
Публикации в категории - {{ category_slug }}
{% endblock %}

{% block page_header %}
<h1>Публикации в категории - {{ category_slug }}</h1>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}
{{ post.location }}. {{ post.date }}
{% endblock %}

{% block content %}
<article>
  <ul>
    <li>
      {{ post.location }}
    </li>
    <li>
      {{ post.date }}
    </li>
    <li>
      Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
    </li>
  </ul>
  <p>
    {{ post.text }}
  </p>
</article>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}

{% block title %}
Лента записей
{% endblock %}

{% block page_header %}
<h1>Лента записей</h1>
{% endblock %}

{% block content %}

{% for post in posts %}
<hr>
<article>
  <ul>
    <li>
      Место: {{ post.location }}
    </li>
    <li>
      Дата: {{ post.date }}
    </li>
    <li>
      Категория: <a href="{% url 'blog:category_posts' category_slug=post.category %}">{{ post.category }}</a>
    </li>
  </ul>
  <p>
    {{ post.text|truncatewords:10 }}
  </p>
  <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
</article>

{% endfor %}

{% endblock %}

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>
</footer>

blogicum/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      <ul class="nav  nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'index:index' %}active{% endif %}" href="{% url 'index:index' %}">
            Лента записей
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'pages:about' %}active{% endif %}" href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'pages:rules' %}active{% endif %}" href="{% url 'pages:rules' %}">
            Наши правила
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

{% endwith %}

blogicum/templates/pages/about.html
{% extends "base.html" %}

{% block title %}
О проекте
{% endblock %}

{% block page_header %}
<h1>О проекте</h1>
{% endblock %}

{% block content %}
<p>
  Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
  нет грани между ведением блога и дружбой в социальных сетях.
</p>
<p>
  Дружба и рассказы о новых, неизведанных впечатлениях — вот
  что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам.
  Путешествия, политики, развлечения, мода, мода, литература, дизайн и все
  другие сферы человеческой деятельности.
</p>
<p>
  Творчество, разнообразие и свобода взглядов и самовыражения —
  основные черты наших пользователей.
</p>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}

{% block title %}
Наши правила
{% endblock %}

{% block page_header %}
<h1>Наши правила</h1>
{% endblock %}

{% block content %}
<p>
  <b>Cамовыражение.</b> У наших пользователей должна
  быть возможность создать что-то своё, выразить себя,
  свои мысли и чувства.
</p>
<p>
  <b>Многообразие.</b> Мы уважаем и приветствуем разные
  мнения и культуры. Блогикум — это место, объединяющее
  самых разных людей. Поделитесь своим уникальным взглядом на мир.
</p>
<p>
  <b>Творчество.</b> Не важно, в какой области вы творите,
  это может быть литература, дизайн, программирование.
  Наши инструменты помогут вам раскрыть талант максимально
  просто и комфортно.
</p>
<p>
  <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
  Делитесь своей информацией только с теми, кого выбрали.
  Как и насколько засекречивать вашу личную информацию —
  определяете вы и только вы.
</p>
{% endblock %}